### ISSUE TITLE
Can dart_eval support await?

### ISSUE THREAD

**Issue by goflutterjava** [ethanblake4/dart_eval#10]
Thanks for your reply :)

**Comment by ethanblake4** [comment]
Hi!

The current AST implementation of dart_eval will soon be replaced by the [dbc-ir](https://github.com/ethanblake4/dart_eval/tree/dbc-ir) bytecode interpreter version, hopefully within a month. I am currently working on the implementation of closures there, and you can expect that it will support basic callback-based concurrency using Future.then() at or shortly after launch. Async/await will come sometime after.

**Comment by goflutterjava** [comment]
@ethanblake4 Thanks for your reply :), when I use `futuer.then()`, It comes an error `Unknown field 'then'`. Which means I need to define `future` in Parser, Are there already-defined future in this library

**Comment by ethanblake4** [comment]
Correct, it does not have it right now. It will have it in about a month, in the new version which also has a lot of other changes.

Defining it as a bridge class yourself in Parser might work, but neither master or dbc-ir branch supports closures yet. I think (maybe) the master branch supports tear-offs so you might be able to use that.

**Comment by goflutterjava** [comment]
looking forward to your great work! Thanks
