### ISSUE TITLE
dart_eval doesn't support external libraries

### ISSUE THREAD

**Issue by kazemcodes** [ethanblake4/dart_eval#101]
if it's possible, try to add a way to use external libraries in the dart_eval ( only libraries that are available in the projects pubspec )

**Comment by taosimple** [comment]
Use `Bridge` can resolve this issue

**Comment by kazemcodes** [comment]
> Use `Bridge` can resolve this issue

Do you mean create a local wrapper around the external library function or classes we want and use that wrapper function in the eval?

**Comment by taosimple** [comment]
Yes, using the librarys in a local function and then calling this function through a bridge should work. However, I found that this library has too many bugs and needs to be careful.

**Comment by ethanblake4** [comment]
Closing as duplicate of #21
