### ISSUE TITLE
Unknown field '&&'

### ISSUE THREAD

**Issue by chuangers** [ethanblake4/dart_eval#11]
I have this expression : "if (x>=50 && x<65) {return '-1';}" and when I want to scope '&&'  isn't recognize.

The stacktrace :
![image](https://user-images.githubusercontent.com/95850980/149165428-62d770ec-f810-4e80-a22d-6d55e87ca0a2.png)

Thank you for your reply.

**Comment by ethanblake4** [comment]
Hi!

The current implementation of dart_eval will be shortly replaced by the [dbc-ir](https://github.com/ethanblake4/dart_eval/tree/dbc-ir) bytecode interpreter version. So, I am not going to make any updates to this version personally. But if you want I am happy to accept a PR, the relevant code to add is in EvalBool in the primitives.dart file.
