### ISSUE TITLE
RuntimeTypes for list is missing

### ISSUE THREAD

**Issue by IndroidsRohan03** [ethanblake4/dart_eval#114]
RuntimeTypes as a list is missing..

/// Bridged runtime type IDs for core Dart types.
class RuntimeTypes {
  /// Bridged runtime type for [void]
  static const int voidType = -1;

  /// Bridged runtime type for [dynamic]
  static const int dynamicType = -2;

  /// Bridged runtime type for [null]
  static const int nullType = -3;

  /// Bridged runtime type for [Object]
  static const int objectType = -4;

  /// Bridged runtime type for [bool]
  static const int boolType = -5;

  /// Bridged runtime type for [num]
  static const int numType = -6;

  /// Bridged runtime type for [String]
  static const int stringType = -7;

  /// Bridged runtime type for [int]
  static const int intType = -8;

  /// Bridged runtime type for [double]
  static const int doubleType = -9;

  /// Bridged runtime type for [Map]
  static const int mapType = -10;

  /// Bridged runtime type for [Function]
  static const int functionType = -12;

  /// Bridged runtime type for [Type]
  static const int typeType = -13;

  /// Bridged runtime type for [Future]
  static const int futureType = -16;

  /// Bridged runtime type for [Duration]
  static const int durationType = -17;

  /// Bridged runtime type for [Enum]
  static const int enumType = -18;
}

**Comment by ethanblake4** [comment]
Hey, it's available as a type spec via CoreTypes.list. You can use `BridgeTypeRef(CoreTypes.list)`. RuntimeTypes is being deleted entirely in v0.7.0 to resolve the confusion :)
