### ISSUE TITLE
Looking to Collaborate

### ISSUE THREAD

**Issue by chgibb** [ethanblake4/dart_eval#12]
Hi @ethanblake4 ! I think we exchanged some posts over Reddit about a year ago (and what a long year it's been).

I'm a huge fan of your work! I think it's amazing that you're building a DBC interpreter in Dart!

I'm building [Hydro-SDK](https://hydro-sdk.io/). Hydro-SDK aims to allow developers to author Flutter content and to [publish and update that content over the air](https://hydro-sdk.io/blog/fluttering-over-the-air) (outside the app stores). I gave a [talk about Hydro-SDK last year at DartUP](https://hydro-sdk.io/blog/dartup-2021) (where I also mentioned `dart_eval`  🙂 ).

Hydro-SDK accomplishes this by providing [an embedded Lua interpreter written in Dart](https://hydro-sdk.io/docs/design-documents/cfr) and a [toolchain to compile Typescript to Lua, compile, package and distribute code](https://hydro-sdk.io/docs/sdk-tools). The Lua VM supports [hot reload](https://hydro-sdk.io/blog/mangling-dynamic-language-symbols) with some [limitations](https://hydro-sdk.io/docs/edge-cases-and-errors). There's some [limitations](https://hydro-sdk.io/docs/limitations) to the Typescript support as well.

I've been focused the last year on building out tools for [automatic binding generation](https://hydro-sdk.io/docs/design-documents/swid/) to allow using arbitrary Dart packages with Hydro-SDK.

Everything about Hydro-SDK aims to be as language agnostic as possible. I would love to collaborate on embedding `dart_eval` into Hydro-SDK later this year if you're interested. At the very least, I'd love to compare notes with you on binding systems and VMs. 🙂

**Comment by ethanblake4** [comment]
Hey @chgibb ! Of course I remember - it was our conversation that inspired me to start building the bytecode VM version, and I've been a fan of Hydro for a while. In fact I was thinking of reaching out to you about some sort of integration as well :)

I do want to make the note that what I have is not a [DBC bytecode](https://github.com/dart-lang/sdk/issues/35773) interpreter - actually, I didn't even realize that existed until now, and I guess I should change the name :p My 'DBC' is a custom bytecode format created specifically for dart_eval, which at the very least makes the interop stuff a lot easier.

Anyways - I'd love to chat! My ideas for integration were mostly limited to the Hydro package registry but I'm open to something deeper too if it makes sense. Shoot me an email - ethanblake [at] gmail.com. Happy to set up a time for VC or just email.

**Comment by chgibb** [comment]
The fact that it is a custom bytecode format is even more impressive! I've sent you an email 🙂
