### ISSUE TITLE
An example for implementing Flutter with this lib

### ISSUE THREAD

**Issue by SahajRana** [ethanblake4/dart_eval#15]
Hi @ethanblake4, this is truly a great lib & exactly what I was looking for. You have mentioned that we can use Flutter widgets with this lib. I tried to add them using the example you have mentioned. But from my approach, it seems I have to add boilerplate code for all the required Widgets ie for text, container, etc. Is there a better way to approach this? Could you share an example, if possible? Thanks.

**Comment by ethanblake4** [comment]
Hi @SahajRana, thanks for the kind words. Unfortunately that is currently the only way to do it. I am collaborating with Hydro SDK to integrate automatic binding generation and hope to get it done within a few months. In the meantime I suggest you use Hydro SDK for Flutter codepush, if you're OK with using Typescript.

**Comment by SahajRana** [comment]
@ethanblake4, Typescript is the biggest reason I'm not using Hydro & came for this lib. As it would mean to code in two languages a single functionality. I believe that what you are doing here is the right recipe for code push as it will save people from using two different languages (Using typescript would also make using flutter of no use, as then in my opinion one can go with react-native path). 

Could you share an example with Flutter widgets as I'm not able to get it right yet?

**Comment by SahajRana** [comment]
Thanks for the share! I will follow this example to get things done for now. Eagerly waiting for in-built flutter support on it.🤞 I would try to contribute to this lib in my free time.

**Comment by SahajRana** [comment]
@ethanblake4, it seems like the `dart_eval` lib doesn't support a lot of functionality yet like maths, string interpolation, etc. I tried `dbc-ir` lib, but it seems to have changed a lot of classes & implementations in it. So, the given example wasn't working with it. I tried to update with `dbc-ir` counterparts, but was not able to completely convert it. If you could share an example with flutter implementation on `dbc-ir` that would be really helpful.

**Comment by ethanblake4** [comment]
Thanks for the feedback. Yes, dart_eval is missing a lot of features right now. I also wouldn't suggest trying to use `dbc-ir` since it mostly has the same limitations and even more than the default version.

If there are specific features you are looking for please let me know and I will prioritize them; but generally it will take probably ~a year before dart_eval covers the majority of the Dart language.

**Comment by SahajRana** [comment]
@ethanblake4, have you looked into [https://pub.dev/packages/petitparser](url) & [https://pub.dev/packages/expressions](url). I have used them & they might help you with dart expressions implementation & might save a lot of time. The big problem with them is that they can do all kinds of expressions but not classes or functions which this lib does. So, if you can combine both (this lib & petitparser), it could be awesome. 
I'm trying to create a simulator that could take code and map it on the screen, without building it like Flutter does.

**Comment by ethanblake4** [comment]
I am using the Dart analyzer package which already does most of the work in terms of parsing, expression types and operator precedence etc. So, those libs would not be helpful (and probably not possible to integrate well). Thanks for the suggestion though.

If you are looking for a way to be able to put in any generic Flutter code and have it function, that's not going to be possible for a while, it just is a lot of work and there's no shortcut. However if it is limited to a small subset of Flutter code it can work great.

If you want to help out to move the project faster I can point to where to start. But even in that case it will be many months of work.

**Comment by SahajRana** [comment]
@ethanblake4, I would love to contribute to it as for me it is inevitable to create a sim. It's just a question of priority. Nevertheless, I think, I might be able to start working on it from Feb or maybe sooner depending on the priority list.
 
Just to mention, I meant evaluation of the expressions in this [https://pub.dev/packages/expressions](https://pub.dev/packages/expressions) like maths, logical-relational operators, etc which seems to be already added to `dbc-ir` as well.

**Comment by ethanblake4** [comment]
Ok cool, well certainly let me know :)

I know, the problem with that package though is it just doesn't support all the things we need. Like it will work fine if you are just doing `2 + 2`, but what if you did `2 + [new DateTime()][0].millisecondsSinceEpoch`? That's perfectly valid Dart code so I hope you can see why it wouldn't work.

**Comment by soahyle** [comment]
> ... I am collaborating with Hydro SDK to integrate automatic binding generation and hope to get it done within a few months...

Hi @ethanblake4, could I ask how Hydro SDK helps to solve the problem? I would like to try out Hydro SDK, but I prefer Dart more instead of TS.

**Comment by ethanblake4** [comment]
Closing in favor of #22 and #20
