### ISSUE TITLE
$List<E>  add element failed  in dart_eval ,throw type '$Data' is not a subtype of type 'Data' of 'value'

### ISSUE THREAD

**Issue by yanweimin7** [ethanblake4/dart_eval#176]
**sorry my pool english**

I want add a element to list(exist outside of dart_eval) in dart_eval runtime.
i use code like this 
```dart
 final a = Data();
 a.name = "c";
DataManager().dataList.add(a);
```
it throw error:
```
type '$Data' is not a subtype of type 'Data' of 'value'
```

DataManager:

```dart
@Bind()
class DataManager {
  static final DataManager singleton = DataManager.internal();

  factory DataManager() {
    return singleton;
  }
  DataManager.internal();

  List<Data> dataList = [];
}

```

i think it's a bug from $List 
![image](https://github.com/ethanblake4/dart_eval/assets/1791581/0e31f545-66e6-4cfa-beb2-fe2437dce398)

when add element ,its should add value.$value.
```dart
(target!.$value as List).add(value.$value);
```

**Comment by ethanblake4** [comment]
Fixed in v0.7.5 using the new writeback-capable `$List.view()` (see #162). If you re-run `dart_eval bind` it should automatically generate this for you.
