### ISSUE TITLE
How to define a future type when using bridge mode

### ISSUE THREAD

**Issue by goflutterjava** [ethanblake4/dart_eval#18]
```
BridgeTypeAnnotation($TimestampedTime.$type, false)
```
I saw the example in `dart_eval_example`, how to define a type which returns `Future<String>`

**Comment by ethanblake4** [comment]
`BridgeTypeAnnotation(BridgeTypeReference.unresolved(BridgeUnresolvedTypeReference('dart:core', 'Future'), []), false)`.

Currently only `Future` is supported not `Future<String>`, but it works like Future<dynamic> so it can support any type.
