### ISSUE TITLE
when to support call method in dart_eval runtime

### ISSUE THREAD

**Issue by yanweimin7** [ethanblake4/dart_eval#182]
currently i saw all method are throw UnimplementedError

![image](https://github.com/ethanblake4/dart_eval/assets/1791581/4ece1d3f-69a5-472b-a103-e0cc12ee3797)

**Comment by ethanblake4** [comment]
Currently these cannot be auto-generated because there are a lot of edge cases. I am working on it, but in the meantime you have to write the code for this yourself (you can look through the dart_eval and flutter_eval codebase to see examples of how to do it)

**Comment by yanweimin7** [comment]
got it! ,  thanks!

> Currently these cannot be auto-generated because there are a lot of edge cases. I am working on it, but in the meantime you have to write the code for this yourself (you can look through the dart_eval and flutter_eval codebase to see examples of how to do it)
