### ISSUE TITLE
Could not find declaration "File" at unknown (file package:example/main.dart)

### ISSUE THREAD

**Issue by cattlelovegrass** [ethanblake4/dart_eval#188]
File("asset/3.0x/battery_box_bg.png");

**Comment by cattlelovegrass** [comment]
> Did you import dart:io?

YES, this library is Imported

**Comment by cattlelovegrass** [comment]
Error: dart_eval runtime exception: RangeError (index): Index out of range: no indices are valid: 0
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 600:7            _get]
packages/dart_eval/src/eval/shared/stdlib/io/file.dart 276:32                $new
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/dart_eval/src/eval/runtime/runtime.dart 832:7                       execute
packages/dart_eval/src/eval/runtime/runtime.dart 810:12                      executeLib
packages/example/main.dart 146:10

**Comment by cattlelovegrass** [comment]
I add breakpoint, It throws error:
  static $File $new(Runtime runtime, $Value? target, List<$Value?> args) {
    return $File.wrap(File(args[0]!.$value));
  }
List<$Value?> args   IS Empty,  the console shows args size is  0

**Comment by ethanblake4** [comment]
Yes ok I will fix that.
You cannot use `File` when compiling to Web / JS platform though.

**Comment by cattlelovegrass** [comment]
> Yes ok I will fix that. You cannot use `File` when compiling to Web / JS platform though.

constructors: {
        '': BridgeConstructorDef(BridgeFunctionDef(
            returns: BridgeTypeAnnotation($type), params: [
          BridgeParameter('path',
              BridgeTypeAnnotation(BridgeTypeRef(CoreTypes.string)), false),
        ], namedParams: []))
      },  You just add path  to Constructor params, then args[0] is not empty,

**Comment by cattlelovegrass** [comment]
closed

**Comment by ethanblake4** [comment]
This fix is now released in version 0.7.7
