### ISSUE TITLE
what is the difference between  $int($value.hashCode) and __hashCode ?

### ISSUE THREAD

**Issue by HXiaoMing** [ethanblake4/dart_eval#190]
$Object $getProperty method:
```
@override
  $Value? $getProperty(Runtime runtime, String identifier) {
    switch (identifier) {
      case 'hashCode':
       return __hashCode;
    }
  }

  static const $Function __hashCode = $Function(_hashCode);

  static $Value? _hashCode(
      Runtime runtime, $Value? target, List<$Value?> args) {
    return $int(target!.$value.hashCode);
  }

```

```
@override
  $Value? $getProperty(Runtime runtime, String identifier) {
    switch (identifier) {
      case 'hashCode':
        return $int($value.hashCode);
    }
  }
```
I don't understand, what is the difference between  __hashCode and  $int($value.hashCode) ?
It confuses me a long time.If I want to write a Wrapper, which way is better?

And How to write a Wrapper to the follow TestClass class?
especially the 'addListener' method, please help me.
```
typedef Listener = int Function(int aaa);

@Bind()
class TestClass {
  Listener addListener(Listener listener) {
    return listener;
  }
}


/// dart_eval wrapper binding for [TestClass]
class $TestClass implements $Instance {

  @override
  $Value? $getProperty(Runtime runtime, String identifier) {
    switch (identifier) {
      case 'addListener':
        return __addListener;
    }
    throw UnimplementedError();
  }

  late final $Function __addListener = $Function(_addListener);
  
  $Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
    /// I don't know how to write here
    return const $null();
  }
  
}

```

**Comment by ethanblake4** [comment]
`$Function __hashCode` is correct if `hashCode` was a method that you call like `x.hashCode()`.

This was a mistake because it's actually a getter that you access like `x.hashCode`, for that we use `$int($value.hashCode)`.

For addListener you would do something like:
```dart
static const $Function __addListener = $Function(_addListener);
  
$Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
  final self = target!.$value as TestClass;
  final listener = args[0] as EvalCallable;
  self.addListener((aaa) {
    return listener.call(runtime, null, [$int(aaa)])!.$value;
  });
}
```

**Comment by HXiaoMing** [comment]
> `$Function __hashCode` is correct if `hashCode` was a method that you call like `x.hashCode()`. `$Function __hashCode` 如果 `hashCode` 是您调用的方法，则 `x.hashCode()` 正确。
> 
> This was a mistake because it's actually a getter that you access like `x.hashCode`, for that we use `$int($value.hashCode)`.这是一个错误，因为它实际上是您访问的吸气剂，例如 `x.hashCode` ，我们使用 `$int($value.hashCode)` .
> 
> For addListener you would do something like:对于 addListener，您可以执行如下操作：
> 
> ```dart
> static const $Function __addListener = $Function(_addListener);
>   
> static $Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
>   final self = target!.$value as TestClass;
>   final listener = args[0] as EvalCallable;
>   self.addListener((aaa) {
>     return listener.call(runtime, null, [$int(aaa)])!.$value;
>   });
> }
> ```

Thanks your explanation ,I understand it.

The method addListener return Listener.
The Wrapper method _addListener  miss return Listener.
How to return the Listener in _addListener method, it should return like that $Function()?
```
Listener addListener(Listener listener) {
    return listener;
  }

$Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
    final self = target!.$value as TestClass;
    final listener = args[0] as EvalCallable;
    self.addListener((aaa) {
      return listener.call(runtime, null, [$int(aaa)])!.$value;
    });

   /// miss return Listener.  how to write here?

  }

```

**Comment by ethanblake4** [comment]
The simple answer is you can return `args[0] as EvalFunction`.

However, if you are going to pass this result to a `removeListener()` function it won't work. You will have to do some complicated caching stuff for that, you can see how to do it [in the flutter_eval ChangeNotifier wrapper](https://github.com/ethanblake4/flutter_eval/blob/90bd9799e02ee74413c0da17d017e567a9115c4d/lib/src/foundation/change_notifier.dart#L49).

**Comment by HXiaoMing** [comment]
> The simple answer is you can return `args[0] as EvalFunction`.简单的答案是你可以返回 `args[0] as EvalFunction` 。
> 
> However, if you are going to pass this result to a `removeListener()` function it won't work. You will have to do some complicated caching stuff for that, you can see how to do it [in the flutter_eval ChangeNotifier wrapper](https://github.com/ethanblake4/flutter_eval/blob/90bd9799e02ee74413c0da17d017e567a9115c4d/lib/src/foundation/change_notifier.dart#L49).但是，如果您要将此结果传递给 `removeListener()` 函数，它将不起作用。为此，您将不得不做一些复杂的缓存工作，您可以在 flutter_eval ChangeNotifier 包装器中看到如何做到这一点。

Thanks.
If the  method addListener return ListenerB is not Listener.
And how to handle this?
```
typedef Listener = int Function(int aaa);
typedef ListenerB = String Function(String bbb);

ListenerB addListener(Listener listener) {
  return (str) {
    return str;
  };
}
```

**Comment by HXiaoMing** [comment]
> I don't understand, can you please explain more what you mean with the ListenerB thing?我不明白，你能解释一下你对 ListenerB 的意思吗？

It is an example. I actually want to write a Wrapper for the StateNotifier.
The class StateNotifier from a pub package state_notifier
[state_notifier: ^1.0.0](https://pub-web.flutter-io.cn/packages/state_notifier)

And the StateNotifier has a method addListener.
I can not writer the Wrapper because of the addListener method.
I don't known how to write it.

StateNotifier part source code:
```
typedef RemoveListener = void Function();
/// This callback receives the current [StateNotifier.state] as a parameter.
typedef Listener<T> = void Function(T state);

abstract class StateNotifier<T> {
  T _state;
  /// Initialize [state].
  StateNotifier(this._state);
  
  RemoveListener addListener(
      Listener<T> listener, {
        bool fireImmediately = true,
      }) {
    ///...source code
    return () {
      ///...source code
    };
  }
}
```

**Comment by ethanblake4** [comment]
Oh I see. You could do it like this:
```dart
$Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
  final self = target!.$value as StateNotifier;
  final listener = args[0] as EvalCallable;
  final removeListener = self.addListener(() {
      return listener.call(runtime, null, [])!.$value;
  });
  return $Function((runtime, target, args) => removeListener());
}
```

Also you shouldn't have to do the complicated caching stuff with this, so it's actually easier :)

**Comment by HXiaoMing** [comment]
> Oh I see. You could do it like this:哦，我明白。你可以这样做：
> 
> ```dart
> $Value? _addListener(Runtime runtime, $Value? target, List<$Value?> args) {
>   final self = target!.$value as StateNotifier;
>   final listener = args[0] as EvalCallable;
>   final removeListener = self.addListener(() {
>       return listener.call(runtime, null, [])!.$value;
>   });
>   return $Function((runtime, target, args) => removeListener());
> }
> ```
> 
> Also you shouldn't have to do the complicated caching stuff with this, so it's actually easier :)此外，您不必使用它进行复杂的缓存操作，因此实际上更容易:)

thank you so much!!!

**Comment by ethanblake4** [comment]
As of v0.7.8 the binding generator can now automatically generate code to do this
