### ISSUE TITLE
how to write a wrapper for TopLevelVariableDeclaration?

### ISSUE THREAD

**Issue by HXiaoMing** [ethanblake4/dart_eval#193]
for example, globalInt is a TopLevel const. how to write a wrapper for it?
globalInt is define in dart. how to use it in eval?
```
const int globalInt = 111;
```

**Comment by ethanblake4** [comment]
Currently you can only do it with `addSource`, like [here](https://github.com/ethanblake4/dart_eval/blob/0d6861aa2067c0af7e7f9ab30e9a11b1c637ed30/lib/src/eval/shared/stdlib/convert.dart#L9).

If you need to specify the value externally via the bridge, you could use a bridged top-level function:
```dart
class MyPlugin implements EvalPlugin {
  // ...

  @override
  void configureForCompile(BridgeDeclarationRegistry registry) {
    registry.defineBridgeTopLevelFunction(BridgeFunctionDeclaration(
      'package:myapp/functions.dart',
      'getObject',
      BridgeFunctionDef(
          returns: BridgeTypeAnnotation(BridgeTypeRef(CoreTypes.object)), params: [])
    ));

    registry.addSource(DartSource('package:myapp/functions.dart', '''
      const globalObject = getObject();
    '''));
  }

  @override
  void configureForRuntime(Runtime runtime) {
    runtime.registerBridgeFunc('package:myapp/functions.dart', 'getObject', 
        (runtime, target, args) => $Object(getObject()));
  }
}
```

**Comment by HXiaoMing** [comment]
> Currently you can only do it with `addSource`, like [here](https://github.com/ethanblake4/dart_eval/blob/0d6861aa2067c0af7e7f9ab30e9a11b1c637ed30/lib/src/eval/shared/stdlib/convert.dart#L9).
> 
> If you need to specify the value externally via the bridge, you could use a bridged top-level function:
> 
> ```dart
> class MyPlugin implements EvalPlugin {
>   // ...
> 
>   @override
>   void configureForCompile(BridgeDeclarationRegistry registry) {
>     registry.defineBridgeTopLevelFunction(BridgeFunctionDeclaration(
>       'package:myapp/functions.dart',
>       'getObject',
>       BridgeFunctionDef(
>           returns: BridgeTypeAnnotation(BridgeTypeRef(CoreTypes.object)), params: [])
>     ));
> 
>     registry.addSource(DartSource('package:myapp/functions.dart', '''
>       const globalObject = getObject();
>     '''));
>   }
> 
>   @override
>   void configureForRuntime(Runtime runtime) {
>     runtime.registerBridgeFunc('package:myapp/functions.dart', 'getObject', 
>         (runtime, target, args) => $Object(getObject()));
>   }
> }
> ```

thank you so much!!!
