### ISSUE TITLE
Binding generation

### ISSUE THREAD

**Issue by ethanblake4** [ethanblake4/dart_eval#20]
dart_eval should have a tool to scan an existing package (including the Dart and Flutter SDK) and auto-generate bindings. Maybe can use package:build?

(for anyone who finds this: If you need to write bindings right now I suggest using GitHub Copilot, it does a fairly good job generating the boilerplate)

**Comment by DenchikBY** [comment]
Hello! Is there are any eta for this? Wanna to use dio or other http client, but seems have to write too much boilerplate  code for this, or mb exists some other workaround?

**Comment by ethanblake4** [comment]
@DenchikBY no eta sorry, I only work on this in my spare time. Easiest 'workaround' is if you create a function that does the data fetching with Dio you can pass it into an Eval function as an anonymous closure by simply wrapping with $Function and putting in the args array.

**Comment by DenchikBY** [comment]
@ethanblake4 I trying but yet not too deep familiar with bindings, mb you can show me example ho to do that?
Thanks in advance 🙏

**Comment by ethanblake4** [comment]
@DenchikBY you don't need to create bindings for that. Just put something like 
```dart
runtime.executeLib('package:my_package/example.dart', 'someFunction', [$Function((runtime, target, args) async {
   final url = args[0];
   final dio = Dio();
   final response = await Dio.get(url);
   return $String(response.data as String);
})]);
```

And then in the eval code you could just do:
```dart
Future someFunction(Function getWithDio) async {
   print(await getWithDio('https://example.com'));
}
```

**Comment by ethanblake4** [comment]
@narongchiyakul updated my previous comment to fix the error

**Comment by a-wallen** [comment]
Should this be a CLI option?

**Comment by ethanblake4** [comment]
Basic binding generator added to the CLI in v0.7.1 based on @a-wallen's work.
