### ISSUE TITLE
CLI: compile external packages

### ISSUE THREAD

**Issue by ethanblake4** [ethanblake4/dart_eval#21]
The dart_eval CLI should compile app dependencies from Pub, etc. Data about packages created by "pub get" is in .dart_tool/package_config.json.

**Comment by Chappie74** [comment]
Hey thanks for the work you've done. Any timeline on this?

**Comment by ethanblake4** [comment]
@Chappie74 is there specific package(s) you want to be able to use? Right now, adding this wouldn't be that useful because most Pub packages use features that dart_eval doesn't support yet, but if you have a specific package in mind I can work on supporting it.

(Also, most existing packages can be supported already by creating a bridge library like flutter_eval has, but I understand this isn't ideal)

**Comment by Chappie74** [comment]
Hey yes. So i've created [this package ](https://pub.dev/packages/flutter_auto_gui). 
Essentially I want to use it in another application, which allows the user to write/execute dynamic code to say move the mouse. 
I previously had my setup in python, and could just have the user submit python code calling the various functions of the package and then just run it in eval. Similar functionality is needed.

Thanks for the reply.

**Comment by Chappie74** [comment]
Alright. I'll give it a try. I did look over the examples and so forth, but somehow couldn't wrap my head around it. I'll give it another shot for a couple days and reach out if I'm having any troubles. Thanks again.

**Comment by ethanblake4** [comment]
@Chappie74 Yes. Bridging allows you to call *existing* Dart functions (and instantiate existing Dart classes) from dart_eval. It doesn't actually parse any of the code inside those classes or functions, just uses them as is, so they don't have any restrictions on what they can do. 

Plus in this case you also only have to bridge the public API, not any of the platform interface stuff (although i believe you theoretically could do so with no problem).

Also, can you start a Discussion if you have any further Qs? Don't want to crowd this issue. No worries if it's a minor question.

**Comment by ethanblake4** [comment]
Support for Pub packages added in v0.7.0
