### ISSUE TITLE
Support String.substring()

### ISSUE THREAD

**Issue by maks** [ethanblake4/dart_eval#26]
I'm trying to figure out what is supported for core types. Eg I have a simple test harness:
```
import 'package:dart_eval/dart_eval.dart';

void main(List<String> arguments) {
  final program = '''
      int main() {
          // my test code goes here
      }
  ''';

  print("eval result:${eval(program)}");
}
```

If my program text is:
```
bool main() {
        final cat = 'Fluffy';
        return cat.isEmpty;
      }
```
I get the expected result: `eval result:false`

For:
```
String main() {
        final cat = 'Fluffy';
        return cat.substring(0,2);
      }
```
However I get:
```
Unhandled exception:
Null check operator used on a null value
#0      resolveInstanceMethod (package:dart_eval/src/eval/compiler/expression/method_invocation.dart:201:62)
#1      new AlwaysReturnType.fromInstanceMethod (package:dart_eval/src/eval/compiler/type.dart:438:16)
#2      AlwaysReturnType.fromInstanceMethodOrBuiltin (package:dart_eval/src/eval/compiler/type.dart:471:28)
#3      Variable.invoke (package:dart_eval/src/eval/compiler/variable.dart:210:28)
#4      _invokeWithTarget (package:dart_eval/src/eval/compiler/expression/method_invocation.dart:135:14)
#5      compileMethodInvocation (package:dart_eval/src/eval/compiler/expression/method_invocation.dart:29:12)
#6      compileExpression (package:dart_eval/src/eval/compiler/expression/expression.dart:27:12)
#7      compileReturn (package:dart_eval/src/eval/compiler/statement/return.dart:38:17)
#8      compileStatement (package:dart_eval/src/eval/compiler/statement/statement.dart:24:12)
#9      compileBlock (package:dart_eval/src/eval/compiler/statement/block.dart:16:20)
#10     compileFunctionDeclaration (package:dart_eval/src/eval/compiler/declaration/function.dart:49:14)
#11     compileDeclaration (package:dart_eval/src/eval/compiler/declaration/declaration.dart:18:5)
#12     Compiler.compileSources.<anonymous closure>.<anonymous closure> (package:dart_eval/src/eval/compiler/compiler.dart:248:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#14     Compiler.compileSources.<anonymous closure> (package:dart_eval/src/eval/compiler/compiler.dart:237:13)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#16     Compiler.compileSources (package:dart_eval/src/eval/compiler/compiler.dart:234:30)
#17     Compiler.compile (package:dart_eval/src/eval/compiler/compiler.dart:80:12)
#18     eval (package:dart_eval/src/eval/eval.dart:29:28)
#19     main (file:///home/maks/work/dart_eval/example/minimal_example.dart:11:24)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Is this because only Getters/Setters are curently supported?
The reason I'm trying this is to see if its possible now or in future for `dart_eval` to do "transparent" interop with "real dart" code.
I apologise if this is a silly question, as Ihaven't really been able to figure out yet how `dart_eval` calls into "real dart".

**Comment by ethanblake4** [comment]
Thanks for the great Q! This is because there's currently no binding for the `substring` method. To support this you would simply add a known method [here](https://github.com/ethanblake4/dart_eval/blob/06dda6a8a2aaea4f8d0dca947f7efa2e5e932ce8/lib/src/eval/compiler/builtins.dart#L191) and a runtime binding [here](https://github.com/ethanblake4/dart_eval/blob/06dda6a8a2aaea4f8d0dca947f7efa2e5e932ce8/lib/src/eval/shared/stdlib/core/base.dart#L133). That runtime binding is the actual place where dart_eval is "calling into real Dart", btw.

**Comment by maks** [comment]
Awesome! Thanks for the pointers to the bits of the code, thats making more sense now that I know where to look 👍🏻 
And definitely would like to contribute, its a pretty simple addition, but this should help me start to find my way around the codebase.

**Comment by ethanblake4** [comment]
Going to rename this since we covered the title question. Feel free to reach out if you have q's, thanks for wanting to contribute.

ps. I need to revamp the 'known method' system that I pointed you to, ultimately the core types should primarily use the bridge system like [Future already does](https://github.com/ethanblake4/dart_eval/blob/06dda6a8a2aaea4f8d0dca947f7efa2e5e932ce8/lib/src/eval/shared/stdlib/core/future.dart#L20). Still need some plumbing before that can happen though.

**Comment by maks** [comment]
@ethanblake4 I had a go at implementing `substring()` but I seem to have run into an odd issue where the arguments don't seem to be handled correctly. Eg. I have test code like this:
```dart
test('String has substring method', () {
      final exec = compiler.compileWriteAndLoad({
        'example': {
          'main.dart': '''
            int main() {
              String cat = "Fluffy";
              String sub = cat.substring(0,3);
            }
          ''',
        }
      });
      expect(exec.executeLib('package:example/main.dart', 'main'), 3);
    });
```
and I've add my substring impl code to `builtins.dart` and `base.dart` as you suggested like so:
```dart
 static const $Function __substring = $Function(_substring);

  static $Value? _substring(final Runtime runtime, final $Value? target, final List<$Value?> args) {
    target as $String;
    // final start = args[0] as $int;
    // final end = args[1] as $int;
    // print("START:${start.$value} END:${end.$value}");
    return $String(target.$value);
  }
```
Unfort while my `_substring()` in base.dart gets called, its `args` list is empty.

And when I set a break point in `objects.dart` line 84 and then inspect the variables state in the debugger I see for the `pr` prop of `runtime` this (below) and I don't see where the start and end args (0 & 3) are being pushed onto the runtime stack?
Or am I missing something obvious here? (I'm rather new to bytecode interpreter VMs).

![image](https://user-images.githubusercontent.com/71999/172535768-4ccf368d-8eae-4606-9353-b60b2ba8404d.png)

**Comment by ethanblake4** [comment]
Can I see what you put in `builtins.dart`? Maybe you forgot to add the KnownMethodArgs there, if the compiler doesn't know there's supposed to be args it won't handle them.

**Comment by maks** [comment]
@ethanblake4 yes sorry about that, I should have just pushed up my WIP branch. Its here: https://github.com/maks/dart_eval/tree/26-add-string-builtins

But yes I did see that I needed to add `KnownMethodArgs` which you can see I added and set the 2nd on to be optional & nullable and the first to not be. So thats what got me stumped, as I couldn't quite figure out which part of the code makes use of them to put the args onto the stack. I can see the function call being popped off at line 411 in `runtime.dart` but not where the function and its args were supposed to be put on it?

**Comment by ethanblake4** [comment]
Huh, I guess this actually just wasn't implemented for `KnownMethod`s. Good case study in why I want to get rid of it - way too much code that needs to be duplicated. I'm surprised I hadn't encountered this before though.

Anyway, fixed in https://github.com/ethanblake4/dart_eval/commit/bde4006661c1762d70419f39785caaf30fa36a22 :)

**Comment by maks** [comment]
awesome, thanks for fixing that so quickly! 👍🏻 🎉 
I'll try to get this finished off now.

**Comment by maks** [comment]
sorry @ethanblake4 I think this substring implementation is proving trickier than it first looked.
I got it working when passing in both required and optional params, but when omitting the optional param, it throws from a out of bounds array access in here: https://github.com/ethanblake4/dart_eval/blob/master/lib/src/eval/compiler/helpers/argument_list.dart#L134

which makes sense as the optional param is not in the arguments list.
But when I added a check for that: https://github.com/maks/dart_eval/blob/26-add-string-builtins/lib/src/eval/compiler/helpers/argument_list.dart#L134

it only kicked the can down the road to runtime and then I get:
```
dart_eval runtime exception: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _CastListBase.[] (dart:_internal/cast.dart:99:38)

RUNTIME STATE
=============
Program offset: 6
Stack sample: [Instance of '$String', 3, null, null, null, null, null, null, null, null]
Call stack: [0, -1]
TRACE:
0: PushScope (F2:12, 'main()')
1: PushConstant (C0)
2: PushConstantInt (3)
3: BoxInt (L1)
4: PushArg (L1)
5: BoxString (L0)
6: InvokeDynamic (L0.substring)  <<< EXCEPTION
7: PushReturnValue ()
8: PushArg (L2)
9: InvokeExternal (Ex#0)
2

Runtime.execute
package:dart_eval/…/runtime/runtime.dart:419
Runtime.executeNamed
package:dart_eval/…/runtime/runtime.dart:403
Runtime.executeLib
package:dart_eval/…/runtime/runtime.dart:398
main.<fn>.<fn>.<fn>
test/dart_eval_test.dart:556
package:test_api                                        expect
main.<fn>.<fn>
```

So I expect its not enough to just ignore that optional arg at compile time as then something at runtime is still expecting their to have been 2 args pushed onto the VMs stack?

**Comment by ethanblake4** [comment]
> I added a check for that

That's a super elegant solution thanks! I'll probably reuse that in other places since dart_eval doesn't really support optional positional parameters at all currently.

As far as the error, looks like it got cut off. With the next line included it's:
```
dart_eval runtime exception: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _CastListBase.[] (dart:_internal/cast.dart:99:38)
#2      $String._substring (package:dart_eval/src/eval/shared/stdlib/core/base.dart:164:21)
```

I suspect you can figure out exactly what the fix is now :)

**Comment by maks** [comment]
doh! 🤦🏻‍♂️ how foolish of me and super annoying the VSCode terminal cutoff that line, no idea why it did that.
Anyways the PR is ready now: https://github.com/ethanblake4/dart_eval/pull/35

Thanks @ethanblake4 for your help with it, it's been a very valuable learning experience!

If it makes sense I can add in support for the remaining String methods or did you mention you were working on a better way to implement the standard lib classes?

**Comment by ethanblake4** [comment]
@maks merged it! thank you!

Also don't blame VS Code, the cutoff is [my fault](https://github.com/ethanblake4/dart_eval/blob/62e0149867a758627576e9496c2837b52b4089b2/lib/src/eval/runtime/runtime.dart#L514). I found 3 lines to be less annoying since I'm usually looking more at the dart_eval debug info, but it should probably have a better heuristic.

Go ahead that'd be fantastic! Replacing KnownMethod isn't at the top of my priority list and even then the runtime bindings will stay.
