### ISSUE TITLE
add CI to run tests

### ISSUE THREAD

**Issue by maks** [ethanblake4/dart_eval#28]

**Comment by ethanblake4** [comment]
Hm, looks like the workflow you added doesn't work since this repo was made before `master` was changed to `main`, and your action uses `main`. Can you please create a new PR to fix?

I'm testing with https://github.com/ethanblake4/dart_eval/pull/31 which fixes #27.

**Comment by maks** [comment]
oops sorry I completely missed the difference in branch names! I'll fix that right away

**Comment by maks** [comment]
ok the first run seems to have worked with my PR that fixed the branch name: https://github.com/ethanblake4/dart_eval/actions/runs/2451609736
though of course it failed on running the tests steps.

@ethanblake4 I also commented out the dart format check step as I didn't know if you want to have the formatted rules enforced.

**Comment by ethanblake4** [comment]
sweet! just remade #31 into https://github.com/ethanblake4/dart_eval/pull/33 and all the tests passed :) thanks for your help

**Comment by maks** [comment]
awesome and thank you for working on this so quickly, much appreciated! 👍🏻
