### ISSUE TITLE
Cannot open file, path = 'out.dbc' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by hellokai55** [ethanblake4/dart_eval#42]
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
Cannot open file, path = 'out.dbc' (OS Error: Read-only file system, errno = 30)
════════════════════════════════════════════════════════════════════════════════

**Comment by viniciusamelio** [comment]
im facing the same issue

**Comment by viniciusamelio** [comment]
solved it by reading saved script using the [path_provider](https://pub.dev/packages/path_provider) lib

**Comment by ethanblake4** [comment]
Thanks @viniciusamelio for that solution. The new [flutter_eval](https://pub.dev/packages/flutter_eval) package is the recommended way to use dart_eval in a Flutter context and it uses path_provider internally so I'm gonna close this.
