### ISSUE TITLE
Maybe post and discuss on with community?

### ISSUE THREAD

**Issue by fzyzcjy** [ethanblake4/dart_eval#62]
If this is to be *the* solution of flutter hot update, IMHO discussing with more smart people may be helpful. For example, there may be serious problems that we both have not realized which completely blocks the package - good to know it earlier than later.

In addition, since Hot Update is the most upvoted issue in Flutter repo, I guess there will be some more people interested in this package and have the open-source spirits. Then, this package may have some PR and develop faster, i.e. gain hot-update sooner.

Possible locations that I come up with (probably also other places that I do no know):

* reddit
* dart github repo / flutter dart discord channel - maybe dart team will provide some insights

**Comment by ethanblake4** [comment]
I have made [several](https://www.reddit.com/r/dartlang/comments/na0l5h/introducing_dart_eval_an_extensible_dart/?utm_source=share&utm_medium=web2x&context=3) [Reddit](https://www.reddit.com/r/dartlang/comments/uchl6a/introducing_dart_eval_v02_the_dart_interpreter/?utm_source=share&utm_medium=web2x&context=3) [posts](https://www.reddit.com/r/FlutterDev/comments/wux1vf/introducing_flutter_eval_one_large_step_towards/?utm_source=share&utm_medium=web2x&context=3) [about](https://www.reddit.com/r/FlutterDev/comments/y1g9q3/flutter_eval_v05_web_support_evalpad_tearoffs_and/?utm_source=share&utm_medium=web2x&context=3) it. I think it's likely that more contributions will start once the package is actually useful for a lot of people already, so then they will use it and find some missing thing and come to add it.

> there may be serious problems that we both have not realized which completely blocks the package

It does already work for a lot of cases, so it doesn't seem like it :)

I have had some lengthy discussions with other smart people with relevant experience, for example @chgibb the creator of Hydro SDK. There are a few things that are not going to be perfectly solvable, like returning a class that conforms to multiple interfaces from dart_eval to Dart. But these are not major enough to 'completely block the package' and most of the core features I have already worked out some kind of plan for.

There are also members of the Flutter/Dart team who have expressed interest in at least using dart_eval for their personal projects (eg. isoos, the creator of Pana)

**Comment by fzyzcjy** [comment]
I see. So weird that so many people needs this feature but there are so few upvotes!

That looks quite great - then the risk of having potential big problem is much lower.

**Comment by ethanblake4** [comment]
> So weird that so many people needs this feature but there are so few upvotes!

The impression I've gotten is that a lot of the demand for Flutter code-push comes from China, probably less likely to use reddit? (If you speak Chinese I'd appreciate some insight on this. Maybe I could figure out how get more contributors involved)

**Comment by fzyzcjy** [comment]
> The impression I've gotten is that a lot of the demand for Flutter code-push comes from China, probably less likely to use reddit? (If you speak Chinese I'd appreciate some insight on this. Maybe I could figure out how get more contributors involved)

Yes I do speak Chinese, but I am not sure whether that's true - where do you get that impression of demand from China?

**Comment by ethanblake4** [comment]
Lots of stars on this project from Chinese users, many other Flutter code push solutions are from China (jspatch, chimera, etc). Also comments like https://github.com/flutter/flutter/issues/14330#issuecomment-455405403 . I could be wrong though - I know flutter is generally very popular in China so it may just be that
