### ISSUE TITLE
Make String extend Pattern

### ISSUE THREAD

**Issue by maks** [ethanblake4/dart_eval#68]
A number of core types are not yet supported in `EvalTypes`, but specifically the following are needed to be able to complete for all  methods on String being done in #37 :
* `Pattern`
* `Match`
* `RegExp`
* `Runes`
* `Iterable`

Adding `Iterable` seems to be already covered by #9

**Comment by maks** [comment]
@ethanblake4 I'm thinking I'll just do the ones I can in #37 without these being available and then there can be a followup PR to add the remainder once these are supported.

**Comment by ethanblake4** [comment]
I have in-progress work on all of these except Runes (for now, just doesn't seem like priority). Might be a bit complicated that I'm using the bridge system while string is still KnownMethod but I'll figure something out. Definitely go ahead and do the ones that are possible now, thanks for your help :)

**Comment by maks** [comment]
Yes, definitely I think Runes is hardly used.

I've pushed up commit to PR #36 that now implements most of the String methods, hope that's of help. I'll look out for when the other core classes are ready and happy to circle back to finish off the remainder of the methods.

**Comment by ethanblake4** [comment]
As of v0.6.0 most of these are supported, though it is still impossible to make String (a KnownMethod type) extend Pattern (a bridge type) so I'm going to leave this open and rename it.

**Comment by ethanblake4** [comment]
String now extends Pattern in v0.7.0. Most methods have been updated to match.
