### ISSUE TITLE
Support for arrow function entrypoint in eval()

### ISSUE THREAD

**Issue by DrafaKiller** [ethanblake4/dart_eval#74]
We can't have an **expression body** because it throws a compile error, like
```dart
String main() => 'Hello World!';
```

It only accepts a **block body**, like
```dart
String main() {
  return 'Hello World!';
}
```

### Code
```dart
import 'package:dart_eval/dart_eval.dart';

void main() {
  print(
    eval('''
      String main() => 'Hello World!';
    ''')
  );
}
```

### Error
<details>
<summary>Click to expand</summary>

```
Unhandled exception:
CompileError: Unknown statement type FunctionDeclarationStatementImpl at unknown (file package:default/main.dart)
#0      Compiler.compileSources
package:dart_eval/…/compiler/compiler.dart:344
#1      Compiler.compile
package:dart_eval/…/compiler/compiler.dart:131
#2      eval
package:dart_eval/…/eval/eval.dart:35
#3      main
test\temp.dart:5
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)

#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
Exited (255)
```
</details>

**Comment by ethanblake4** [comment]
Expression body should be supported since version 0.4.6, what version are you using?

This might also just be because you are using the eval() method, can you try using compiler.compile() -> Runtime.ofProgram() -> executeLib() instead? (described more in the readme)

**Comment by ethanblake4** [comment]
Fixed in https://github.com/ethanblake4/dart_eval/commit/4e7d946bb1ebfcb621bc8eae64240283b9a5b9ec and https://github.com/ethanblake4/dart_eval/commit/36e0af75501bceaf159c0f6e1377e8d4b3066126, will be in next release
