### ISSUE TITLE
Remove dcli

### ISSUE THREAD

**Issue by ethanblake4** [ethanblake4/dart_eval#75]
dcli is a [very bloated](https://github.com/onepub-dev/dcli/blob/master/dcli/pubspec.yaml) package with many dependencies that can cause issues, see:

_@anz-ryu's comment in https://github.com/ethanblake4/flutter_eval/issues/17#issuecomment-1302843228_

It should be removed since we are only using a few of its features.

**Comment by maks** [comment]
I used https://pub.dev/packages/cli_repl in my repl package and found it worked quite well and is light weight.
