### ISSUE TITLE
Security Implications?

### ISSUE THREAD

**Issue by anlumo** [ethanblake4/dart_eval#78]
Assuming that I download untrusted code to my Windows application written in Flutter, compile the code using dart_eval and execute it, can it do anything problematic, like access the file system or the network?

As far as I can tell, `dart:io` is not exposed, but is there anything else in there?

**Comment by ethanblake4** [comment]
It cannot (unless you add your own bridge plugins) and it would be considered a security vulnerability if there was some way to achieve network or file access.

Long term, I'm working on a runtime permissions system for when dart:io does eventually get exposed.

**Comment by anlumo** [comment]
Excellent, thank you!
