### ISSUE TITLE
some other dart syntax goodness

### ISSUE THREAD

**Issue by aktxyz** [ethanblake4/dart_eval#80]
It looks like the ?? operator and the the ? : conditional syntax are not yet supported.  I find these used all the time in flutter work, any chance these are on the roadmap ?  Or even some pointers/advice on how to work thru adding these for a PR?

**Comment by ethanblake4** [comment]
I had these on the roadmap for v0.8 (probably about 8 months out).

If you're interested in making a PR this would probably not be a terribly difficult one. Write a test that uses ?? or ?: and see where it errors to get started; then just think about how to desugar it using other existing code as a reference. `??` is basically `if (x == null) y else x` so you can look at how dart_eval handles `if` (if.dart) and `==` (binary.dart).

**Comment by ethanblake4** [comment]
These are both supported in v0.6.2
