### ISSUE TITLE
How to concatenate strings in eval code for async functions?

### ISSUE THREAD

**Issue by StasKalishenko** [ethanblake4/dart_eval#86]
For instance, I'm getting a string from outside (var value is actually $String) using await and trying to concatenate it with string ' suffix'. As a result I'm waiting for Future, but getting exception like '**dart_eval runtime exception: type 'String' is not a subtype of type '$Instance' in type cast'**.
Here the code:
```
Future getTitle() async {
     final value = await TimestampedTime(DateTime.now().millisecondsSinceEpoch, timezoneOffset: 6).getContact();
     return value + ' suffix';
}
```
How to solve it?

**Comment by ethanblake4** [comment]
Can you put the code for getContact()?

**Comment by StasKalishenko** [comment]
Here it is:
```
  $Value? getContact(Runtime runtime, $Value? identifier, List<$Value?> args) =>
    $Future.wrap(_getContact(), $String.new);
```
And _getContact returns String. Like:
```
Future<String> _getContact() async {
  return 'test';
}
```

**Comment by ethanblake4** [comment]
Yes, this is a bug... the second parameter of `Future.wrap()` only works with `then()` currently, not `await`. You'll have to directly return a `$String` from _getContact, or maybe you could do `await x.getContact().then((x) => x)`. Will add to my list to fix properly.

**Comment by StasKalishenko** [comment]
Ok, it’s clear. And what about operations with string in eval code? Can it be compared with other string, with null or can I use ‘contains’? Like 
`if (myString.contains(‘test’)) {…}`
There is no examples and info in docs, that’s why I have so dump questions.

**Comment by ethanblake4** [comment]
Best place to see if a certain feature is supported is to look at the tests: https://github.com/ethanblake4/dart_eval/tree/master/test

For example you can see here that the `contains` method is supported on strings: https://github.com/ethanblake4/dart_eval/blob/eeaf3ed71533c2a966ae46f1d9c9eebee7116160/test/string_test.dart#L112

**Comment by StasKalishenko** [comment]
> Yes, this is a bug... the second parameter of `Future.wrap()` only works with `then()` currently, not `await`. You'll have to directly return a `$String` from _getContact, or maybe you could do `await x.getContact().then((x) => x)`. Will add to my list to fix properly.

I can't change _getContact to return `$String`, 'cause it's always async operation (like the most operations with data). That's why it must return Future.
And `await x.getContact().then((x) => x)` doesn't work for me. I did in eval code:
```
Future getSomeData() {
      return EvalBridgeUtils().getContact().then((String contact) => contact);
} 
```
And outside code:
```
final getSomeDataValue = runtime.executeLib('package:example/main.dart', 'getSomeData') as $Future;
getSomeDataValue.$value.then((value) {
      print('ddd');
});
```
It crashes with "Null check operator used on a null value". Where did I make mistake?

**Comment by ethanblake4** [comment]
Sorry, I meant return `Future<$String>`, not `$String`.

I wasn't totally sure then then() workaround would work.

**Comment by ethanblake4** [comment]
As of v0.6.0, the second parameter of Future.wrap() has been removed. This should clear up the inconsistent behavior. Use of bimodal wrappers or manually mapping to `$Value`s is recommended.
