### ISSUE TITLE
why flutter eval doesn't support network

### ISSUE THREAD

**Issue by HuyDuc111** [ethanblake4/dart_eval#88]
Currently we are developing an app which uses flutter eval to create hostdeploy but flutter eval doesn't support network yet if it is supported we will develop our app even better.

<img width="664" alt="Screenshot 2022-12-20 at 17 21 49" src="https://user-images.githubusercontent.com/71079610/208645716-2cb99bef-eeda-4286-9797-83f64ee73977.png">

**Comment by ethanblake4** [comment]
As of v0.6.0 the dart:io HttpClient class is supported.
