### ISSUE TITLE
Iterable.generate not Implemented

### ISSUE THREAD

**Issue by anlumo** [ethanblake4/dart_eval#91]
https://api.flutter.dev/flutter/dart-core/Iterable/Iterable.generate.html

Test case:

```dart
Iterable.generate(10, (i) => i)
```

results in `UnimplementedError`.

**Comment by wrbl606** [comment]
Hey @ethanblake4, can you assign me to this issue so there's a clear indication that somebody is working on it? 😇

**Comment by ethanblake4** [comment]
@wrbl606 done!

**Comment by ethanblake4** [comment]
Released in v0.7.0
